name: test_new_flutter
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  feature_posts:
    path: feature_posts

  flutter:
    sdk: flutter


dev_dependencies:

  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter: