name: test_new_flutter
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter_bloc: ^8.0.1
  get_it: ^7.2.0
  retrofit: ^3.0.1+1

  flutter:
    sdk: flutter

dev_dependencies:
  #  \/ Need to be in each module where retrofit used.
  #     To have possibility to run
  #     'dart pub run build_runner build --delete-conflicting-outputs'
  #     command for generating *Client.g.dart class. Command can be run when terminal switched to module dir
  build_runner: ^2.2.0
  retrofit_generator: ^4.0.2
  #  /\

  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.1

flutter: