name: feature_posts
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  core_logic:
    path: ../core_logic

  api_test:
    path: ../api_test

dev_dependencies: