name: api_test
description: A new Flutter module project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  build_runner: ^2.1.11
  retrofit_generator: ^4.0.1
  core_api:
    path: ../core_api

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter: