name: core_api
description: A new Flutter module project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  module:
    androidX: true
    androidPackage: com.example.core_api
    iosBundleIdentifier: com.example.coreApi
