name: core_api
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  dio: ^4.0.6
  core_logic:
    path: ../core_logic
  feature_api_interceptors:
    path: ../feature_api_interceptors

dev_dependencies: